[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = { "CPMMD" = "src" }

[project]
name = "CPMMD"
version = "0.2"
authors =  [{name="Koen", email="koen19@gmail.com"}]
description = "An implementation of the coupling between the CPM and a MD based ECM model."

[project.scripts]
cpmmdplot = "CPMMD.plot:main"
cpmmdplot2 = "CPMMD.plot2:cli"
cpmmd = "CPMMD.run:main"
# cpmmdplot_blender = "CPMDMD.scripts.plot"


