#[derive(Debug, Clone, serde::Deserialize)]
pub struct Config {
    pub grid_sizex: usize,
    pub grid_sizey: usize,
    pub grid_sizez: usize,
    pub init_cell_size: usize,
    pub init_cell_number_divisions: usize,
    pub temperature: f64,
    pub target_area_lambda: f64,
    pub target_area: usize,
    pub j_matrix: Vec<f64>,
    pub num_init_adhesions: usize,
    pub init_adhesion_radius: f64,
    pub adhesion_annihilation_penalty: f64,
    pub adhesion_overflow_number: usize,
    pub adhesion_overflow_penalty: f64,
    pub check_connectivity: bool,
    pub target_perimiter: f64,
    pub target_perimiter_lambda: f64,
    pub area_contraction: f64,
    pub adhesion_creation: bool,
    pub max_act: f64,
    pub lambda_act: f64,
    pub mcs: usize,
    pub seed: usize,
}
